version: "3.9"
services:
    fboking:
        image: prueba_spring2
        ports:
            - "8080:8080"
        environment:
            - FBOOKING_DB_NAME=${FBOOKING_DB_NAME}
            - FBOOKING_DB_USER=${FBOOKING_DB_USER}
            - FBOOKING_DB_PASSWORD=${FBOOKING_DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=1
            - DB_HOST=django-db
        depends_on:
            - django-db
        links:
            - django-db

    django-db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=${FBOOKING_DB_NAME}
            - MYSQL_USER=${FBOOKING_DB_USER}
            - MYSQL_PASSWORD=${FBOOKING_DB_PASSWORD}
            - MYSQL_RANDOM_ROOT_PASSWORD=1
        volumes:
            - ../mysql-volume:/var/lib/mysql


