name: CodeClimate Coverage

on:
  push:
    branches:
      - main

jobs:
  codeclimate-coverage:
    name: Upload to CodeClimate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Generate Jacoco Report
        run: mvn test jacoco:report

      - name: Upload Coverage to CodeClimate
        uses: codeclimate/test-reporter-action@v2.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverage_files: ./target/site/jacoco/jacoco.xml